<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <BaseOutputPath>..\stage</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Skia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.12" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Material.Avalonia" Version="3.13.4" />
    <PackageReference Include="Material.Avalonia.Dialogs" Version="3.13.4" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9.5" />
  </ItemGroup>

</Project>
