using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using GrbLHALSender.ViewModels;
using System;
using System.Collections.Specialized;

namespace GrbLHALSender.Views;

/// <summary>
/// Macros for the portrait control block: the caption and the buttons share one wrapping flow,
/// filling across and dropping down as space allows. <see cref="MacroBarView"/> is the
/// landscape equivalent, a single strip beside the tab headers.
/// </summary>
public partial class MacroGridView : UserControl
{
    // Narrower than the landscape bar's 115 so three fit across a ~360px column:
    // 3 * (105 + 8) = 339. At 115 only two fit and the third wraps.
    private const double ButtonWidth = 105;
    private const double ButtonHeight = 40;
    private static readonly Thickness ItemMargin = new(0, 0, 8, 8);

    private MacroViewModel? _macroViewModel;

    public MacroGridView()
    {
        InitializeComponent();
    }

    protected override void OnDataContextChanged(EventArgs e)
    {
        if (_macroViewModel != null)
            _macroViewModel.MacroList.CollectionChanged -= OnMacroListChanged;

        _macroViewModel = (DataContext as MainViewModel)?.MacroViewModel;

        if (_macroViewModel != null)
            _macroViewModel.MacroList.CollectionChanged += OnMacroListChanged;

        Rebuild();
        base.OnDataContextChanged(e);
    }

    private void OnMacroListChanged(object? sender, NotifyCollectionChangedEventArgs e) => Rebuild();

    /// <summary>
    /// Rebuilds the flow from the macro list.
    /// <para>
    /// Children are constructed here rather than generated by an items control because the
    /// "MACROS:" caption has to be part of the same wrapping flow as the buttons, and an items
    /// control only arranges what it generates from its source.
    /// </para>
    /// </summary>
    private void Rebuild()
    {
        Flow.Children.Clear();

        // The caption shows even with no macros defined. Unlike the landscape bar, which hides
        // it so an orphan word does not sit next to the tab headers, this block owns a fixed
        // area of the canvas — leaving it blank would read as dead space rather than as
        // somewhere macros will appear.
        Flow.Children.Add(new Label
        {
            Content = "MACROS:",
            FontSize = Resource("BaseFontSize", 26),
            Height = ButtonHeight,
            VerticalContentAlignment = VerticalAlignment.Center,
            Margin = ItemMargin
        });

        var macros = _macroViewModel?.MacroList;
        if (macros == null)
            return;

        foreach (var macro in macros)
        {
            Flow.Children.Add(new Button
            {
                Content = macro.Id,
                CommandParameter = macro.Id,
                Command = _macroViewModel!.RunMacroCommand,
                Width = ButtonWidth,
                Height = ButtonHeight,
                FontSize = Resource("DetailFontSizeLarge", 22),
                CornerRadius = new CornerRadius(6),
                Margin = ItemMargin,
                HorizontalContentAlignment = HorizontalAlignment.Center,
                VerticalContentAlignment = VerticalAlignment.Center
            });
        }
    }

    /// <summary>
    /// Looks up an app-level font size. These are plain doubles that never change at runtime,
    /// unlike the theme brushes, so a one-time read is enough.
    /// </summary>
    private static double Resource(string key, double fallback) =>
        Application.Current?.TryFindResource(key, out var value) == true && value is double d
            ? d
            : fallback;
}
